# Phil's experimental image
FROM gcr.io/engineering-devops/am-fbc:7.0.0-b88a5200251a75e788da806d60c4c0c7e008ee5e
USER root

RUN apt-get update && apt-get install -y git

USER forgerock

COPY  --chown=forgerock:root config/ /home/forgerock/openam/config/

# Use a custom logback. Comment out if you want to use the default json logger.
COPY logback.xml /usr/local/tomcat/webapps/am/WEB-INF/classes

COPY custom-entrypoint.sh /home/forgerock

WORKDIR /home/forgerock/openam

# This lets the user see what FBC files have been modified
RUN git config --global user.email "cloud-deployment@forgerock.com" && \
    git config --global user.name "Cloud Deployment" && \
    git add . && \
    git commit -m "CDM file-based configuration overlay"

WORKDIR /home/forgerock

ENTRYPOINT ["/home/forgerock/custom-entrypoint.sh"]